### ISSUE TITLE
Less: Support extend feature

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#15]
See docs: http://lesscss.org/features/#extend-feature
CSScomb related issue: https://github.com/csscomb/csscomb.js/issues/222

**Comment by gotbahn** [comment]
Actually it works partially, u can use:

``` css
.foo:extend(.bar) {
    ...
}
```

but next one still get error:

``` css
.foo {
    &:extend(.bar) {
        ...
    }
}
```

**Comment by tonyganch** [comment]
Fixed in `dev`

**Comment by ayjee** [comment]
@tonyganch, any update on when this feature will be released?  I am attempting to use it via the example on the less documentation and it is still failing.

``` css
.animal {
  background-color: black;
  color: white;
}
.bear {
  &:extend(.animal);
  background-color: brown;
}
```
