### ISSUE TITLE
Variable interpolation in SCSS not supported

### ISSUE THREAD

**Issue by kty** [tonyganch/gonzales-pe#56]
Variable interpolation in SCSS doesn't seem to be supported. 

Example code:

``` scss
$classes: .dog, .cat;

#{$classes},
.horse {
    color: red;
}
```

Results in "Parsing error: Please check the validity of the block starting from line #XXX".

**Comment by tonyganch** [comment]
Fixed in `dev` branch: b9b21810636

**Comment by kty** [comment]
Wow, that was almost immediate, thanks!
Just so you know, variable interpolation still isn't supported in media queries, e.g. the `#{$orientation}` part in:

``` scss
@media only screen and (min-device-width: $width) and (orientation:#{$orientation}) {
    @content;
}
```
